
{{- $rname := include "app.fullname" . -}}
{{- $domain := .Values.ingress.domain -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $rname }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- if .Values.ingress.tls }}
    cert-manager.io/issuer: {{ $rname }}-issuer
    cert-manager.io/issue-temporary-certificate: "true"
    {{- end }}
    {{- if .Values.ingress.globalStaticIp }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.globalStaticIp }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.domain }}
    {{ range $mname, $microservice := .Values.microservices -}}
    - {{ $mname }}.{{ $domain }}
    {{ end }}
    {{- if .Values.ingress.tls.production -}}
    secretName: tls-secret-production
    {{- else -}}
    secretName: tls-secret-staging
    {{- end -}}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{$rname}}-web-service
          servicePort: 80
  {{- range $mname, $microservice := .Values.microservices }}
  - host: {{ $mname }}.{{ $domain }}
    http:
      paths:
      - backend:
          serviceName: {{ $rname }}-{{ $mname }}-service
          servicePort: {{ $microservice.port }}
  {{- end }}

{{ if .Values.ingress.tls }}
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $rname }}-issuer
spec:
  acme:
    email: {{ .Values.ingress.tls.email }}
    {{- if .Values.ingress.tls.production }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tls-secret-privatekey-production
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tls-secret-privatekey-staging
    {{- end }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.class }}
{{ end }}
